# Generated by Django 2.1 on 2018-09-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='duty_employees',
        ),
    ]
