# Generated by Django 2.1 on 2018-09-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_workplace_telefon'),
        ('duty', '0002_remove_duty_duty_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='duty',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='dutystaff',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.Duty'),
        ),
        migrations.AddField(
            model_name='dutystaff',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee'),
        ),
        migrations.AddField(
            model_name='dutystaff',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Workplace'),
        ),
    ]
