# Generated by Django 2.1 on 2018-09-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_workplace'),
        ('duty', '0002_remove_duty_duty_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStaff',
            fields=[
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='duty.Duty')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Employee')),
            ],
        ),
    ]
