# Generated by Django 2.1 on 2018-08-21 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20180821_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeout',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выписки'),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='write_out',
            field=models.TextField(default='Выписка...', verbose_name='Выписка'),
        ),
    ]
