# Generated by Django 2.1 on 2018-08-21 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180821_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('write_down', models.TextField(default='Запись...', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Запись СЦБ',
                'verbose_name_plural': 'Записи СЦБ',
            },
        ),
        migrations.AlterModelOptions(
            name='writeout',
            options={'verbose_name': 'Выписка СЦБ', 'verbose_name_plural': 'Выписки СЦБ'},
        ),
    ]
