# Generated by Django 2.1 on 2018-08-22 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20180821_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWriteOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доп. выписки')),
                ('extra_write_out', models.TextField(default='Доп. выписка...', verbose_name='Доп. выписка')),
            ],
            options={
                'verbose_name': 'Доп. выписка СЦБ',
                'verbose_name_plural': 'Доп. выписка СЦБ',
            },
        ),
    ]
