# Generated by Django 2.1 on 2018-08-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_extrawriteout'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeout',
            name='write_down_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.WriteDown'),
            preserve_default=False,
        ),
    ]
