# Generated by Django 2.1 on 2018-08-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_extrawriteout'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeout',
            name='delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='writeout',
            name='write_down_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='journal.WriteDown'),
            preserve_default=False,
        ),
    ]
