# Generated by Django 2.1 on 2018-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20180823_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrawriteout',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writedown',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
