# Generated by Django 2.1 on 2018-08-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_extrawriteout_write_down_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawriteout',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='extrawriteout',
            name='write_down_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.WriteDown', verbose_name='ID записи'),
        ),
        migrations.AlterField(
            model_name='writedown',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='write_down_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.WriteDown', verbose_name='ID записи'),
        ),
    ]
