# Generated by Django 2.1 on 2018-08-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20180823_1558'),
        ('journal', '0006_writeout_write_down_id'),
    ]

    operations = [
    ]
