# Generated by Django 2.1 on 2018-09-03 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20180830_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writedown',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='writedown',
            name='delete',
        ),
        migrations.AddField(
            model_name='writedown',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writedown',
            name='date',
            field=models.DateField(default='2018-09-03', verbose_name='Дата записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writedown',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='writedown',
            name='time',
            field=models.TimeField(default='08:00:00', verbose_name='Время записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writedown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='writedown',
            name='text',
            field=models.TextField(verbose_name='Текст записи'),
        ),
    ]
