# Generated by Django 2.1 on 2018-09-03 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20180903_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrawriteout',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='extrawriteout',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='writeout',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='writeout',
            name='delete',
        ),
        migrations.AddField(
            model_name='extrawriteout',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrawriteout',
            name='date',
            field=models.DateField(default='2018-09-03', verbose_name='Дата доп. выписки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrawriteout',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='extrawriteout',
            name='time',
            field=models.TimeField(default='08:00:00', verbose_name='Время записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrawriteout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='writeout',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writeout',
            name='date',
            field=models.DateField(default='2018-09-03', verbose_name='Дата выписки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writeout',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='writeout',
            name='time',
            field=models.TimeField(default='08:00:00', verbose_name='Время записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writeout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrawriteout',
            name='text',
            field=models.TextField(verbose_name='Текст доп. выписки'),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='text',
            field=models.TextField(verbose_name='Текст выписки'),
        ),
    ]
