# Generated by Django 2.1 on 2018-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20180903_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrawriteout',
            name='time',
            field=models.TimeField(verbose_name='Время доп. выписки'),
        ),
        migrations.AlterField(
            model_name='writeout',
            name='time',
            field=models.TimeField(verbose_name='Время выписки'),
        ),
    ]
