# Generated by Django 2.1 on 2018-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='abbr_worker',
            field=models.CharField(default='ДНЦ', max_length=128, verbose_name='Аббревиатура работника'),
            preserve_default=False,
        ),
    ]
