# Generated by Django 2.1 on 2018-09-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_workplace_abbr_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='abbr_worker',
        ),
    ]
