# Generated by Django 2.1 on 2018-09-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_workplace_abbr_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Organization', verbose_name='Организация'),
        ),
    ]
