# Generated by Django 2.1 on 2018-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_workplace_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='telefon',
            field=models.CharField(default='225-96-96', help_text='Укажите номер в формате 111-11-11', max_length=128, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
