# Generated by Django 2.1 on 2018-09-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название круга')),
            ],
            options={
                'verbose_name': 'Диспетчерский круг',
                'verbose_name_plural': 'Диспетчерские круги',
            },
        ),
        migrations.CreateModel(
            name='SHCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('abbr', models.CharField(max_length=128, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Дистанция сигнализации и связи',
                'verbose_name_plural': 'Дистанции сигнализации и связи',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название станции')),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.Circle', verbose_name='Диспетчерский круг')),
                ('shch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.SHCH', verbose_name='Дистанция сигнализации и связи')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
    ]
