# Generated by Django 2.1 on 2018-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='telefon',
            field=models.CharField(default='225-  -  ', help_text='Укажите номер в формате 111-11-11', max_length=128, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
