# Generated by Django 2.1 on 2018-09-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_circle_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='telefon',
        ),
    ]
